apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ldlwtb8jr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ldlwtb8jr-go 
  name: ldlwtb8jr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ldlwtb8jr-go 
