apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ldlwtb8jr-go 
  janus-idp.io/tekton: ldlwtb8jr-go
  backstage.io/kubernetes-id: ldlwtb8jr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ldlwtb8jr-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml